### ISSUE TITLE
TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by sksarath** [marmelab/react-md-motion#1]
when i clone the repo and run the command npm start.  I am geeting TypeError: Super expression must either be null or a function, not undefined.
<img width="1042" alt="error" src="https://user-images.githubusercontent.com/7887699/34035747-148c8a1a-e1a9-11e7-9ec4-d2e1f4464959.png">

**Comment by floo51** [comment]
Hello ! Thanks for your input, it should be fixed now.
